import { StatusBar } from "expo-status-bar";
import * as SecureStore from "expo-secure-store";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, AppState, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { getHistory, getPatient, GuardianEvent, GuardianStatus, login } from "./src/api";

const TOKEN_KEY = "guardian_token";
const SERVER_KEY = "server_url";
const PUBLIC_API_URL = process.env.EXPO_PUBLIC_API_URL?.replace(/\/$/, "") ?? "";
const stateLabels: Record<string, string> = { STABLE: "안정", AWAY: "자리 비움", WARD_NOTIFIED: "병동 확인 요청", STAFF_CHECKING: "담당자 확인 중", CHECK_COMPLETED: "확인 완료" };
const progressLabels: Record<string, string> = { OPEN: "병동에 확인 요청이 전달되었습니다.", ACKNOWLEDGED: "담당자가 알림을 확인했습니다.", RESPONDING: "담당자가 환자 상태를 확인하고 있습니다.", COMPLETED: "상태 확인이 완료되었습니다.", FALSE_ALARM: "확인 결과 특이사항이 없었습니다." };

export default function App() {
  const [token, setToken] = useState<string | null>(null);
  const [baseUrl, setBaseUrl] = useState(PUBLIC_API_URL || "http://192.168.0.10:8000");
  const [code, setCode] = useState("CARE-101");
  const [status, setStatus] = useState<GuardianStatus | null>(null);
  const [history, setHistory] = useState<GuardianEvent[]>([]);
  const [tab, setTab] = useState<"status" | "history" | "settings">("status");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => { (async () => { const [savedToken, savedUrl] = await Promise.all([SecureStore.getItemAsync(TOKEN_KEY), SecureStore.getItemAsync(SERVER_KEY)]); if (!PUBLIC_API_URL && savedUrl) setBaseUrl(savedUrl); setToken(savedToken); setLoading(false); })(); }, []);
  useEffect(() => { if (!token) return; const refresh = async () => { try { const [patient, events] = await Promise.all([getPatient(baseUrl, token), getHistory(baseUrl, token)]); setStatus(patient); setHistory(events); setError(""); } catch (e) { if ((e as Error).message === "SESSION_EXPIRED") await signOut(); else setError((e as Error).message); } }; refresh(); const timer = setInterval(refresh, 5000); const listener = AppState.addEventListener("change", state => state === "active" && refresh()); return () => { clearInterval(timer); listener.remove(); }; }, [token, baseUrl]);

  async function connect() { setLoading(true); setError(""); try { const result = await login(baseUrl, code); await Promise.all([SecureStore.setItemAsync(TOKEN_KEY, result.access_token), SecureStore.setItemAsync(SERVER_KEY, baseUrl)]); setToken(result.access_token); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  async function signOut() { await SecureStore.deleteItemAsync(TOKEN_KEY); setToken(null); setStatus(null); setHistory([]); }

  if (loading) return <SafeAreaView style={styles.center}><ActivityIndicator color="#3157d5" size="large" /></SafeAreaView>;
  if (!token) return <SafeAreaView style={styles.page}><StatusBar style="dark" /><ScrollView contentContainerStyle={styles.login}><Text style={styles.brand}>CARE SIGNAL</Text><Text style={styles.title}>보호자 안심 알림</Text><View style={styles.card}><Text style={styles.heading}>환자 연결</Text><Text style={styles.muted}>병동에서 받은 연결 코드를 입력해 주세요.</Text>{!PUBLIC_API_URL && <><Text style={styles.label}>개발 서버 주소</Text><TextInput style={styles.input} value={baseUrl} onChangeText={setBaseUrl} autoCapitalize="none" keyboardType="url" /></>}<Text style={styles.label}>연결 코드</Text><TextInput style={styles.input} value={code} onChangeText={setCode} autoCapitalize="characters" />{!!error && <Text style={styles.error}>{error}</Text>}<Pressable style={styles.button} onPress={connect}><Text style={styles.buttonText}>연결하기</Text></Pressable></View></ScrollView></SafeAreaView>;

  return <SafeAreaView style={styles.page}><StatusBar style="dark" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.brand}>CARE SIGNAL</Text>{tab === "status" && <><Text style={styles.title}>환자 상태</Text>{status ? <View style={styles.card}><Text style={styles.muted}>{status.patient.room_label}</Text><Text style={styles.patient}>{status.patient.display_name} 님</Text><View style={[styles.badge, badgeStyle(status.display_state)]}><Text style={styles.badgeText}>{stateLabels[status.display_state]}</Text></View><Text style={styles.message}>{status.message}</Text><InfoRow label="병실 센서" value={status.sensor_online ? "정상" : "연결 확인 필요"} /><InfoRow label="마지막 갱신" value={new Date(status.updated_at).toLocaleTimeString()} /></View> : <ActivityIndicator />}{status?.event && <View style={styles.card}><Text style={styles.heading}>병동 대응 현황</Text><Text style={styles.messageSmall}>{progressLabels[status.event.progress]}</Text></View>}</>}{tab === "history" && <><Text style={styles.title}>최근 알림</Text>{history.length ? history.map(item => <View style={styles.card} key={item.id}><Text style={styles.heading}>{item.summary}</Text><Text style={styles.muted}>{new Date(item.created_at).toLocaleString()}</Text><Text style={styles.progress}>{progressLabels[item.progress] ?? item.progress}</Text></View>) : <View style={styles.card}><Text style={styles.muted}>최근 알림이 없습니다.</Text></View>}</>}{tab === "settings" && <><Text style={styles.title}>설정</Text><View style={styles.card}><InfoRow label="서버" value={baseUrl} /><Pressable style={styles.outlineButton} onPress={signOut}><Text style={styles.outlineText}>환자 연결 해제</Text></Pressable></View></>}{!!error && <Text style={styles.error}>{error}</Text>}</ScrollView><View style={styles.nav}><Nav label="현재 상태" active={tab === "status"} onPress={() => setTab("status")} /><Nav label="알림 내역" active={tab === "history"} onPress={() => setTab("history")} /><Nav label="설정" active={tab === "settings"} onPress={() => setTab("settings")} /></View></SafeAreaView>;
}

function InfoRow({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.muted}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function Nav({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable style={styles.navItem} onPress={onPress}><Text style={[styles.navText, active && styles.navActive]}>{label}</Text></Pressable>; }
function badgeStyle(state: string) { if (state === "WARD_NOTIFIED") return { backgroundColor: "#fff0d4" }; if (state === "STAFF_CHECKING") return { backgroundColor: "#e5ebff" }; if (state === "AWAY") return { backgroundColor: "#e9edf3" }; return { backgroundColor: "#dcf5e9" }; }

const styles = StyleSheet.create({ page:{flex:1,backgroundColor:"#f2f5fa"},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{padding:22,paddingBottom:110},login:{padding:24,justifyContent:"center",flexGrow:1},brand:{fontSize:14,fontWeight:"800",color:"#3157d5",letterSpacing:1.3},title:{fontSize:28,fontWeight:"800",color:"#17213a",marginTop:7,marginBottom:22},card:{backgroundColor:"white",padding:22,borderRadius:22,marginBottom:15,shadowColor:"#17213a",shadowOpacity:.07,shadowRadius:18,elevation:2},heading:{fontSize:19,fontWeight:"700",color:"#17213a",marginBottom:8},patient:{fontSize:26,fontWeight:"800",marginTop:5,marginBottom:14},muted:{color:"#68758c",lineHeight:21},label:{fontWeight:"700",marginTop:17,marginBottom:7},input:{borderWidth:1,borderColor:"#cbd3e0",borderRadius:12,padding:14,fontSize:16,backgroundColor:"#fff"},button:{backgroundColor:"#3157d5",borderRadius:13,padding:15,alignItems:"center",marginTop:18},buttonText:{color:"white",fontWeight:"800",fontSize:16},error:{color:"#c53b3b",marginVertical:10},badge:{alignSelf:"flex-start",paddingHorizontal:12,paddingVertical:8,borderRadius:30},badgeText:{fontWeight:"800",color:"#25425f"},message:{fontSize:19,lineHeight:30,marginVertical:22,color:"#26324a"},messageSmall:{fontSize:17,lineHeight:27,color:"#26324a"},row:{flexDirection:"row",justifyContent:"space-between",gap:20,borderTopWidth:1,borderTopColor:"#edf0f5",paddingVertical:14},value:{fontWeight:"700",color:"#26324a",flexShrink:1,textAlign:"right"},progress:{marginTop:12,color:"#3157d5",fontWeight:"700"},outlineButton:{borderWidth:1,borderColor:"#3157d5",borderRadius:12,padding:14,alignItems:"center",marginTop:18},outlineText:{color:"#3157d5",fontWeight:"800"},nav:{position:"absolute",bottom:0,left:0,right:0,height:78,backgroundColor:"white",flexDirection:"row",borderTopWidth:1,borderTopColor:"#e6eaf0",paddingBottom:10},navItem:{flex:1,alignItems:"center",justifyContent:"center"},navText:{color:"#8390a5",fontWeight:"700"},navActive:{color:"#3157d5"} });
